name: Deploy to EC2

on:
  push:
    branches: [ production ]  # master에서 production으로 변경하여 일시 비활성화

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USERNAME }}
        SCRIPT_AFTER: |
          cd ~/crata-backend
          git pull origin master
          npm install
          npm run build
          pm2 stop crata-api || true
          pm2 delete crata-api || true
          pm2 start dist/main.js --name crata-api
          pm2 save